// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'eye_exam.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_EyeExam _$EyeExamFromJson(Map<String, dynamic> json) => _EyeExam(
  id: json['id'] as String,
  visitId: json['visit_id'] as String,
  patientId: json['patient_id'] as String,
  doctorId: json['doctor_id'] as String?,
  examDate: json['exam_date'] as String?,
  complaints: json['complaints'] as String?,
  anamnesis: json['anamnesis'] as String?,
  odVa: json['od_va'] as String?,
  osVa: json['os_va'] as String?,
  odSph: json['od_sph'] as String?,
  osSph: json['os_sph'] as String?,
  odCyl: json['od_cyl'] as String?,
  osCyl: json['os_cyl'] as String?,
  odAxis: (json['od_axis'] as num?)?.toInt(),
  osAxis: (json['os_axis'] as num?)?.toInt(),
  odVaCc: json['od_va_cc'] as String?,
  osVaCc: json['os_va_cc'] as String?,
  odVaOwn: json['od_va_own'] as String?,
  osVaOwn: json['os_va_own'] as String?,
  visualField: json['visual_field'] as String?,
  iopOd: json['iop_od'] as String?,
  iopOs: json['iop_os'] as String?,
  orbit: json['orbit'] as String?,
  eyeball: json['eyeball'] as String?,
  eyelids: json['eyelids'] as String?,
  conjunctiva: json['conjunctiva'] as String?,
  lacrimal: json['lacrimal'] as String?,
  cornea: json['cornea'] as String?,
  anteriorChamber: json['anterior_chamber'] as String?,
  iris: json['iris'] as String?,
  pupil: json['pupil'] as String?,
  lens: json['lens'] as String?,
  vitreous: json['vitreous'] as String?,
  fundus: json['fundus'] as String?,
  abScanNote: json['ab_scan_note'] as String?,
  diagnosis: json['diagnosis'] as String?,
  icd10: json['icd10'] as String?,
  recommendations: json['recommendations'] as String?,
  createdAt: json['created_at'] as String?,
  updatedAt: json['updated_at'] as String?,
);

Map<String, dynamic> _$EyeExamToJson(_EyeExam instance) => <String, dynamic>{
  'id': instance.id,
  'visit_id': instance.visitId,
  'patient_id': instance.patientId,
  'doctor_id': instance.doctorId,
  'exam_date': instance.examDate,
  'complaints': instance.complaints,
  'anamnesis': instance.anamnesis,
  'od_va': instance.odVa,
  'os_va': instance.osVa,
  'od_sph': instance.odSph,
  'os_sph': instance.osSph,
  'od_cyl': instance.odCyl,
  'os_cyl': instance.osCyl,
  'od_axis': instance.odAxis,
  'os_axis': instance.osAxis,
  'od_va_cc': instance.odVaCc,
  'os_va_cc': instance.osVaCc,
  'od_va_own': instance.odVaOwn,
  'os_va_own': instance.osVaOwn,
  'visual_field': instance.visualField,
  'iop_od': instance.iopOd,
  'iop_os': instance.iopOs,
  'orbit': instance.orbit,
  'eyeball': instance.eyeball,
  'eyelids': instance.eyelids,
  'conjunctiva': instance.conjunctiva,
  'lacrimal': instance.lacrimal,
  'cornea': instance.cornea,
  'anterior_chamber': instance.anteriorChamber,
  'iris': instance.iris,
  'pupil': instance.pupil,
  'lens': instance.lens,
  'vitreous': instance.vitreous,
  'fundus': instance.fundus,
  'ab_scan_note': instance.abScanNote,
  'diagnosis': instance.diagnosis,
  'icd10': instance.icd10,
  'recommendations': instance.recommendations,
  'created_at': instance.createdAt,
  'updated_at': instance.updatedAt,
};
