"""operations, operation types, treatments

Revision ID: 05b09883d438
Revises: 3a0bb6d0414f
Create Date: 2026-06-12 14:47:07.537753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b09883d438'
down_revision: Union[str, Sequence[str], None] = '3a0bb6d0414f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_types',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_types_code'), ['code'], unique=True)

    op.create_table('operation_type_consumables',
    sa.Column('operation_type_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_type_consumables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_type_consumables_operation_type_id'), ['operation_type_id'], unique=False)

    op.create_table('treatments',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_visit_id'), ['visit_id'], unique=False)

    op.create_table('operations',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('operation_type_id', sa.Uuid(), nullable=False),
    sa.Column('eye', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visit_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_item_id'], ['visit_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_visit_id'))
        batch_op.drop_index(batch_op.f('ix_operations_status'))
        batch_op.drop_index(batch_op.f('ix_operations_patient_id'))

    op.drop_table('operations')
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatments_visit_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_status'))
        batch_op.drop_index(batch_op.f('ix_treatments_patient_id'))

    op.drop_table('treatments')
    with op.batch_alter_table('operation_type_consumables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_type_consumables_operation_type_id'))

    op.drop_table('operation_type_consumables')
    with op.batch_alter_table('operation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_types_code'))

    op.drop_table('operation_types')
    # ### end Alembic commands ###
