"""queue ticket assigned_user_id routing

Revision ID: 68f53379eef0
Revises: c3d263ff86ac
Create Date: 2026-06-13 22:46:05.369247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f53379eef0'
down_revision: Union[str, Sequence[str], None] = 'c3d263ff86ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable, без server_default: существующие талоны остаются NULL = общий
    # пул, ровно текущее поведение очереди. Маршрутизация к конкретному
    # специалисту — опциональная, заполняется ресепшеном/диагностом.
    with op.batch_alter_table('queue_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_queue_tickets_assigned_user_id_users', 'users',
            ['assigned_user_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_queue_tickets_assigned_user_id_users', type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
