"""queue tracks + called_by + operation priority

Revision ID: c0b92f987706
Revises: f30af4b194a3
Create Date: 2026-06-12 16:50:52.896005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b92f987706'
down_revision: Union[str, Sequence[str], None] = 'f30af4b194a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default'ы обязательны: таблицы непустые, NOT NULL без дефолта
    # упал бы на существующих строках. Исторические талоны становятся
    # track='doctor' (они уже done — на витрины не влияют).
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=12),
                                      nullable=False, server_default='normal'))

    with op.batch_alter_table('queue_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.String(length=12),
                                      nullable=False, server_default='doctor'))
        batch_op.add_column(sa.Column('called_by_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_queue_tickets_track'), ['track'], unique=False)
        batch_op.create_foreign_key(
            'fk_queue_tickets_called_by_id_users', 'users',
            ['called_by_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_queue_tickets_called_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_queue_tickets_track'))
        batch_op.drop_column('called_by_id')
        batch_op.drop_column('track')

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
