"""exam_templates

Revision ID: c3d263ff86ac
Revises: f9fca415b2ef
Create Date: 2026-06-13 21:45:03.842903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d263ff86ac'
down_revision: Union[str, Sequence[str], None] = 'f9fca415b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_templates',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('icd10', sa.String(length=16), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_templates_doctor_id'), ['doctor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_templates_doctor_id'))

    op.drop_table('exam_templates')
    # ### end Alembic commands ###
