"""visit flow_status

Revision ID: c8b78621c775
Revises: c0b92f987706
Create Date: 2026-06-12 18:11:08.499150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b78621c775'
down_revision: Union[str, Sequence[str], None] = 'c0b92f987706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: таблица непустая (NOT NULL упал бы на
    # существующих строках); исторические визиты получают 'registered'.
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_status', sa.String(length=24),
                                      nullable=False, server_default='registered'))
        batch_op.create_index(batch_op.f('ix_visits_flow_status'), ['flow_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_flow_status'))
        batch_op.drop_column('flow_status')

    # ### end Alembic commands ###
