"""face_terminals + user.faceid_employee_no

Revision ID: f9fca415b2ef
Revises: 573b0c777a5e
Create Date: 2026-06-13 17:38:05.603234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fca415b2ef'
down_revision: Union[str, Sequence[str], None] = '573b0c777a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_terminals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('door_no', sa.Integer(), nullable=False),
    sa.Column('use_https', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_terminals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_terminals_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faceid_employee_no', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_faceid_employee_no'), ['faceid_employee_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_faceid_employee_no'))
        batch_op.drop_column('faceid_employee_no')

    with op.batch_alter_table('face_terminals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_terminals_status'))

    op.drop_table('face_terminals')
    # ### end Alembic commands ###
