"""treatment optional billing service_id unit_price visit_item_id

Revision ID: fc73b7daceb4
Revises: e9b4c2a7f1d8
Create Date: 2026-06-27 11:43:22.724821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc73b7daceb4'
down_revision: Union[str, Sequence[str], None] = 'e9b4c2a7f1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('visit_item_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_treatments_service_id_services', 'services',
            ['service_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(
            'fk_treatments_visit_item_id_visit_items', 'visit_items',
            ['visit_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_treatments_visit_item_id_visit_items', type_='foreignkey')
        batch_op.drop_constraint('fk_treatments_service_id_services', type_='foreignkey')
        batch_op.drop_column('visit_item_id')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
